version: '3.8'

services:
  mybrain:
    build: .
    container_name: mybrain-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - TZ=Europe/Warsaw
      - ENABLE_BOT=true  # <--- ADD THIS LINE